---

- name: Create VM
  hosts: localhost
  gather_facts: False
  connection: local

  tasks:
    - name: create VM
      uri:
        url: "{{ base_url }}/vms"
        validate_certs: no
        force_basic_auth: yes
        method: POST
        status_code: 202
        user: "{{ username }}"
        password: "{{ password }}"
        return_content: yes
        body: 
          api_version: '3.1.0'
          metadata:
            kind: vm
          spec:
            cluster_reference:
              kind: cluster
              uuid: 00056ae0-7952-1f8a-0000-000000016b6d
            name: testansible1
            resources:
              disk_list:
              - data_source_reference:
                  kind: image
                  uuid: {{ image_uuid }}
                  name: string
                disk_size_mib: 0
                disk_size_bytes: 0
              nic_list:
              - ip_endpoint_list:
                - ip: 192.168.1.100
                subnet_reference:
                  kind: subnet
                  uuid: 59a03db1-209c-4b3a-9ad9-a811380a6e5d
              num_sockets: 1
              num_vcpus_per_socket: 1
              memory_size_mib: 2048
              power_state: 'ON'
        body_format: json
